# Generated by Django 2.1.5 on 2019-05-31 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tito', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('mute_time', models.DateTimeField(verbose_name='date mute')),
            ],
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
