# Generated by Django 2.1.5 on 2019-05-31 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tito', '0002_auto_20190531_0215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='id',
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
